name: shared_storage_windows
description: Flutter network service discovery plugin (Windows submodule - will be installed with the parent plugin).
version: 2.0.1
repository: https://github.com/sebastianhaberey/shared_storage/tree/main/shared_storage_windows
issue_tracker: https://github.com/sebastianhaberey/shared_storage/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: NsdWindowsPluginCApi
