# see https://www.linkedin.com/pulse/github-actions-flutter-app-moataz-nabil
# see https://github.com/felangel/bloc/blob/master/.github/workflows/flutter_bloc.yaml
# see https://github.com/ReactiveCircus/android-emulator-runner

name: Android Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "shared_storage_android/**"

env:
  flutter_channel: "stable" # 'dev', 'alpha', 'stable'
  flutter_version: "3.7.8"
  api_level: "33"
  target: google_apis
  arch: x86_64
  profile: pixel_6 # run 'avdmanager list device' to see profiles

jobs:
  test:
    name: Run integration tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: shared_storage/example

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Set up AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.api_level }}

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Show Flutter configuration
        run: flutter doctor -v

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api_level }}
          target: ${{ env.target }}
          arch: ${{ env.arch }}
          profile: ${{ env.profile }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          working-directory: shared_storage/example
          api-level: ${{ env.api_level }}
          target: ${{ env.target }}
          arch: ${{ env.arch }}
          profile: ${{ env.profile }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: flutter test --no-pub --reporter expanded integration_test/shared_storage_test.dart
