# see https://www.linkedin.com/pulse/github-actions-flutter-app-moataz-nabil
# see https://github.com/felangel/bloc/blob/master/.github/workflows/flutter_bloc.yaml

name: Windows Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "shared_storage_windows/**"

env:
  flutter_version: "3.7.8"

jobs:
  test:
    name: Run tests (Windows)
    runs-on: windows-2022
    defaults:
      run:
        working-directory: shared_storage/example

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # 'dev', 'alpha', 'stable'
          flutter-version: ${{ env.flutter_version }}

      - name: Show Flutter configuration
        run: flutter doctor -v

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub --device-id windows --reporter expanded integration_test/shared_storage_test.dart
